spring:
  application.name: catmash

spring.profiles.active: dev

legacy:
  latelier:
    url: https://latelier.co
    connectTimeOutMillis: 120000
    readTimeOutMillis: 120000

feign:
  hystrix:
    enabled: true


spring.profile: dev
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLiteDialect
spring.datasource.url: jdbc:sqlite:mydb.db
spring.datasource.username:
spring.datasource.password:
spring.datasource.driverClassName: org.sqlite.JDBC
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
